name: Check RETCODE
description: Verifica códigos de retorno usando una lista en un archivo JSON

inputs:
  retcode:
    description: Código de retorno a evaluar
    required: true
  config_file:
    description: Ruta al archivo JSON de configuración
    required: false
    default: 'codes.json'

outputs:
  status:
    description: Estado de la verificación
    value: ${{ steps.check.outputs.status }}
  message:
    description: Mensaje descriptivo del resultado
    value: ${{ steps.check.outputs.message }}
  title:
    description: Título del resultado
    value: ${{ steps.check.outputs.title }}

runs:
  using: "composite"
  steps:
    - name: Check return code
      id: check
      shell: bash
      run: |
        bash "${{ github.action_path }}/check-retcode.sh" "${{ inputs.retcode }}" "${{ inputs.config_file }}"