name: ShellCheck

on:
  push:
    branches:
      - "feature/check-retcode"
  pull_request:
    branches:
      - "feature/check-retcode"
  workflow_dispatch:

jobs:
  lint:
    name: Run ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          severity: style
          scandir: .github/actions/check-retcode